enhavo_resource:
    resources:
        enhavo_revision.archive:
            priority: -10
            classes:
                model: Enhavo\Bundle\RevisionBundle\Entity\Archive
    grids:
        enhavo_revision.archive:
            resource: enhavo_revision.archive
            filters:
                title:
                    type: text
                    property: title
                    label: Text
            columns:
                type:
                    type: Enhavo\Bundle\RevisionBundle\Column\Type\RevisionAwareColumnType
                    width: 4
                title:
                    type: text
                    label: archive.label.title
                    translation_domain: EnhavoRevisionBundle
                    property: title
                    width: 7
                    sortable: true
                date:
                    label: archive.label.date
                    translation_domain: EnhavoRevisionBundle
                    property: date
                    type: datetime
                    width: 3
                    sortable: true
                actions:
                    width: 4
                    type: action
                    actions:
                        restore:
                            type: Enhavo\Bundle\RevisionBundle\Action\Type\RevisionAwareRestoreActionType
                            route: enhavo_revision_admin_api_archive_restore
                            confirm_message: archive.message.confirm
            batches:
                delete:
                    type: delete
