enhavo_revision_admin_api_archive_index:
    path: /archive/index
    methods: [GET]
    defaults:
        _expose: admin_api
        _endpoint:
            type: resource_index
            grid: enhavo_revision.archive

enhavo_revision_admin_api_archive_list:
    path: /archive/list
    methods: [GET,POST]
    defaults:
        _expose: admin_api
        _endpoint:
            type: resource_list
            grid: enhavo_revision.archive

enhavo_revision_admin_api_archive_delete:
    path: /archive/delete/{id}
    methods: [DELETE, POST]
    defaults:
        _expose: admin_api
        _endpoint:
            type: resource_delete
            input: enhavo_revision.archive

enhavo_revision_admin_api_archive_batch:
    path: /archive/batch
    methods: [POST]
    defaults:
        _expose: admin_api
        _endpoint:
            type: resource_batch
            grid: enhavo_revision.archive

enhavo_revision_admin_api_archive_restore:
    path: /archive/restore/{id}
    methods: [POST]
    defaults:
        _expose: admin_api
        _endpoint:
            type: Enhavo\Bundle\RevisionBundle\Endpoint\Type\RevisionAwareRestoreType
            resource: enhavo_revision.archive
            method: dearchive
